version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras --group docs
    install:
      - "true"

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub
